### PR TITLE
Add ics download button...

### PR DESCRIPTION
**Pull request by paulpaul168**
...since I don't like to be bothered to manually enter it in my calendar ;)

### CODE REVIEW

**Comment by flofriday** [comment]
I don't think I can merge this right now 😞 

This is because till now I have treated the _date_ just as text that needs to be understandable by humans. So `new Date(event.date)` in your PR wouldn't be able to parse the date I have currently set in production.

So I will think about an solution because in theory this button would be amazing. 

Really, thank you for your contribution, it might just take some days to merge :(

**Comment by paulpaul168** [comment]
I'm sorry to hear that! I just tested it using a date formatted the same way as it's written in the birthdaiii-example.json file.

**Comment by paulpaul168** [comment]
I made the parsing more robust and decided it might be the best idea to just hide the button if the parsing should fail.

**Comment by flofriday** [comment]
**@paulpaul168 I unmerged this PR**

The PR apparently isn't type-safe, and the deployment failed.
You can try fixing the issue and open a new PR.

I know this is also partly my fault because the CI only deploys and never runs any checks on PR's until they are merged.

**Pull request merged**
